FROM ubuntu:16.04
MAINTAINER eduard.hirsch@fh-salzburg.ac.at
RUN apt-get update
RUN apt-get install curl -y
RUN apt-get install sudo -y
RUN apt-get install software-properties-common -y

#intall hyperledger prereqs-ubuntu
RUN cd /root && \
    curl -O https://hyperledger.github.io/composer/latest/prereqs-ubuntu.sh && \
    chmod u+x prereqs-ubuntu.sh && \
    ./prereqs-ubuntu.sh

CMD ["service", "docker", "start"]
